<?php
require_once _PS_MODULE_DIR_.'profileadv/classes/MenuConstants.php';

class RecommendedProductRules
{
    public static function getRules(): array
    {
        return [
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5, 4],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PIENSO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_GUAUCAT_COCINADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_BAF,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_GUAUCAT_CRUDO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_BAF,
                'price' => 4.64,
            ],
            // Allergy based rules for small puppies
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado azul'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado azul'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado azul'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado azul'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_NOESTERILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado azul'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado azul'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO10KG1A_ESTILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado azul'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO5KG1A_ESTILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado azul'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_CACHORRO10KG1A_ESTILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            // Medium puppies (3-12 months)
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 5],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_PIENSO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_GUAUCAT_COCINADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_BAF,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_GUAUCAT_CRUDO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 5],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_COCINADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_BAF,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_CRUDO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [1, 5],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PIENSO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_GUAUCAT_COCINADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_BAF,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_GUAUCAT_CRUDO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_COCINADO_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_CRUDO_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_GUAUCAT_COCINADO_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_BAF_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_ESTILIZADO_GUAUCAT_CRUDO_ALERGIA_POLLO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 3,
                    'age_max' => 12,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_CACHORRO25KG3M1A_NOESTERILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],

            // Adult small dogs with allergies - pollo
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            // Senior small dogs (>=9 years)
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_PIENSO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_COCINADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_BAF,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 5],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_PIENSO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_GUAUCAT_CRUDO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_BAF,
                'price' => 4.06,
            ],
            // Senior small dogs with chicken allergy
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_POLLO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_BAF_ALERGIA_POLLO,
                'price' => 4.06,
            ],
            // Senior small dogs with fish allergy
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 5],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO,
                'price' => 4.06,
            ],
            // Overweight senior small dogs
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 5],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_PIENSO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_BAF_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_GUAUCAT_CRUDO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_PIENSO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_BAF_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_CRUDO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_GUAUCAT_COCINADO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_BAF_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_ESTILIZADO_GUAUCAT_CRUDO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_PIENSO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_BAF_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR5KGM9A_NOESTERILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_PIENSO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_BAF_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 2,
                    'age_min' => 108,
                    'age_max' => 999,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_SENIOR10KG9A_ESTILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.06,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PIENSO_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pollo'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_BAF_ALERGIA_POLLO,
                'price' => 4.64,
            ],
            // Adult small dogs with allergies - pescado
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_PELUDO_TRABAJO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                    'activity_min' => 3,
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 4.64,
            ],
            // Overweight adult small dogs - no sterilized
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_GUAUCAT_COCINADO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_BAF_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_BAF_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_NOESTERILIZADO_BAF_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.64,
            ],
            // Overweight adult small dogs - sterilized
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_GUAUCAT_COCINADO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_BAF_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_GUAUCAT_COCINADO_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pollo'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT5KGM1A_ESTILIZADO_BAF_ALERGIA_POLLO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 4, 5],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT10KG1A_ESTILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 1,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'physical_in' => ['Gordito'],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_PETIT_ADULT10KG1A_ESTILIZADO_BAF_ALERGIA_PESCADO_SOBREPESO,
                'price' => 4.64,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_PELUDO_TRABAJO_PIENSO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_PELUDO_TRABAJO_BAF,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_PELUDO_TRABAJO_GUAUCAT_CRUDO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_PELUDO_TRABAJO_GUAUCAT_COCINADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [1, 2, 5],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_ESTILIZADO_PELUDO_TRABAJO_PIENSO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [3],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_ESTILIZADO_PELUDO_TRABAJO_BAF,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [4],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_CRUDO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 1,
                    'feeding_in' => [2],
                    'activity_max' => 2,
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_ESTILIZADO_PELUDO_TRABAJO_GUAUCAT_COCINADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [1, 2, 5],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_PIENSO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [2],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_GUAUCAT_COCINADO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [3],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_BAF_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
            [
                'conditions' => [
                    'type' => 1,
                    'size' => 3,
                    'age_min' => 12,
                    'age_max' => 108,
                    'esterilized' => 2,
                    'feeding_in' => [4],
                    'allergies_in' => ['Pescado'],
                ],
                'product' => ProfileadvMenuConstants::MENU_MITJA_ADULT25KG1A_NOESTERILIZADO_GUAUCAT_CRUDO_ALERGIA_PESCADO,
                'price' => 5.60,
            ],
        ];
    }
}
