<?php

/*
--> Type
    --> 1 = dog
    --> 2 = cat
--> Breed
    --> Id from translations/translations.php
--> Size
    --> 1 = Mini - All cats have this size
    --> 2 = Pequeño
    --> 3 = Mediano
    --> 4 = Grande
    --> 5 = Gigante
    --> 6 = Galgos/Podencos
*/

return array(
    array('type' => 1, 'breed' => 1, 'min_male' => 2, 5, 'min_female' => 2, 5, 'avg' => 25, 'size' => 1, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Mezcla Mini (<5KG)'),
    array('type' => 1, 'breed' => 2, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Mezcla Pequeño(5-15KG)'),
    array('type' => 1, 'breed' => 3, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Mezcla Mediano (15-30KG)'),
    array('type' => 1, 'breed' => 4, 'min_male' => 40, 'min_female' => 40, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Mezcla Grande (30-50KG)'),
    array('type' => 1, 'breed' => 5, 'min_male' => 60, 'min_female' => 60, 'avg' => 60, 'size' => 5, 'min_weight' => '48', 'max_weight' => '72', 'breed_name' => 'Mezcla Gigante(>50KG)'),
    array('type' => 1, 'breed' => 6, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Affenpinscher (3.2KG - 4.8KG)'),
    array('type' => 1, 'breed' => 8, 'min_male' => 18, 'min_female' => 17, 'avg' => 17, 5, 'size' => 3, 'min_weight' => '14', 'max_weight' => '21', 'breed_name' => 'Airedale Terrier (21KG 28 KG)'),
    array('type' => 1, 'breed' => 9, 'min_male' => 45, 'min_female' => 45, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Akita Americano (35KG - 64KG)'),
    array('type' => 1, 'breed' => 10, 'min_male' => 32, 'min_female' => 28, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Akita Inu (24KG - 36KG)'),
    array('type' => 1, 'breed' => 11, 'min_male' => 35, 'min_female' => 28, 'avg' => 31, 5, 'size' => 4, 'min_weight' => '25,2', 'max_weight' => '37,8', 'breed_name' => 'Alano español (25.2KG - 37.8KG)'),
    array('type' => 1, 'breed' => 12, 'min_male' => 34, 'min_female' => 34, 'avg' => 34, 'size' => 4, 'min_weight' => '27,2', 'max_weight' => '40,8', 'breed_name' => 'Alaskan Malamute (27.2KG - 40.8KG)'),
    array('type' => 1, 'breed' => 13, 'min_male' => 31, 'min_female' => 27, 'avg' => 29, 'size' => 4, 'min_weight' => '23,2', 'max_weight' => '34,8', 'breed_name' => 'American Bully (20.2KG - 44.8KG)'),
    array('type' => 1, 'breed' => 14, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 4, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'American Foxhound (22KG - 33KG)'),
    array('type' => 1, 'breed' => 15, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'American Pitbull Terrier (16KG - 24KG)'),
    array('type' => 1, 'breed' => 16, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'American Staffordshire Terrier (18KG - 32KG)'),
    array('type' => 1, 'breed' => 17, 'min_male' => 30, 'min_female' => 26, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Antiguo perro de muestra danés (22.4KG - 34.6KG)'),
    array('type' => 1, 'breed' => 18, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Australian Silky Terrier (3.2KG - 7.6KG)'),
    array('type' => 1, 'breed' => 19, 'min_male' => 20, 'min_female' => 15, 'avg' => 17, 5, 'size' => 3, 'min_weight' => '14', 'max_weight' => '21', 'breed_name' => 'Azawakh (14KG - 21KG)'),
    array('type' => 1, 'breed' => 20, 'min_male' => 18, 'min_female' => 16, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Grifon Azul de Gascuña (18KG - 25KG)'),
    array('type' => 1, 'breed' => 22, 'min_male' => 10, 'min_female' => 9, 'avg' => 9, 5, 'size' => 2, 'min_weight' => '7,6', 'max_weight' => '11,4', 'breed_name' => 'Basenji (7.6KG - 12.4KG)'),
    array('type' => 1, 'breed' => 23, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Basset artesiano de Normandía (15KG - 20KG)'),
    array('type' => 1, 'breed' => 24, 'min_male' => 17, 'min_female' => 17, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Basset azul de Gascuña (13.6KG - 20.4KG)'),
    array('type' => 1, 'breed' => 25, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Basset tejonero de los Alpes (12KG - 18KG)'),
    array('type' => 1, 'breed' => 26, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Basset Hound (20KG - 30KG)'),
    array('type' => 1, 'breed' => 27, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 2, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Basset leonado de Bretaña (11.2KG - 17.8KG)'),
    array('type' => 1, 'breed' => 28, 'min_male' => 13, 'min_female' => 12, 'avg' => 12, 5, 'size' => 3, 'min_weight' => '10', 'max_weight' => '15', 'breed_name' => 'Beagle (11KG - 18KG)'),
    array('type' => 1, 'breed' => 29, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Beagle-Harrier (18.4KG - 23.6KG)'),
    array('type' => 1, 'breed' => 30, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Beauceron (24KG - 42KG)'),
    array('type' => 1, 'breed' => 31, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Bedlington Terrier (6.4KG - 10KG)'),
    array('type' => 1, 'breed' => 32, 'min_male' => 32, 'min_female' => 26, 'avg' => 29, 'size' => 3, 'min_weight' => '23,2', 'max_weight' => '34,8', 'breed_name' => 'Bergamasco (23.2KG - 34.8KG)'),
    array('type' => 1, 'breed' => 33, 'min_male' => 26, 'min_female' => 26, 'avg' => 26, 'size' => 4, 'min_weight' => '20,8', 'max_weight' => '31,2', 'breed_name' => 'Berger de Picardie (20.8KG - 31.2KG)'),
    array('type' => 1, 'breed' => 34, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Bernedoodle (24KG - 36KG)'),
    array('type' => 1, 'breed' => 35, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Bichón boloñés (1.6KG - 4KG)'),
    array('type' => 1, 'breed' => 36, 'min_male' => 5, 'min_female' => 4, 'avg' => 4, 5, 'size' => 1, 'min_weight' => '3,6', 'max_weight' => '5,4', 'breed_name' => 'Bichón frisé (3.6KG - 7.4KG)'),
    array('type' => 1, 'breed' => 37, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Bichón Habanero (3.2KG - 7.8KG)'),
    array('type' => 1, 'breed' => 38, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Bichón maltés (2.4KG - 4.6KG)'),
    array('type' => 1, 'breed' => 39, 'min_male' => 33, 'min_female' => 33, 'avg' => 33, 'size' => 4, 'min_weight' => '26,4', 'max_weight' => '39,6', 'breed_name' => 'Billy (26.4KG - 39.6KG)'),
    array('type' => 1, 'breed' => 40, 'min_male' => 29, 'min_female' => 29, 'avg' => 29, 'size' => 4, 'min_weight' => '23,2', 'max_weight' => '34,8', 'breed_name' => 'Black and Tan Coonhound (23.2KG - 34.8KG)'),
    array('type' => 1, 'breed' => 41, 'min_male' => 46, 'min_female' => 39, 'avg' => 42, 5, 'size' => 4, 'min_weight' => '34', 'max_weight' => '51', 'breed_name' => 'Perro de San Huberto (Bloodhound) (34KG - 51KG)'),
    array('type' => 1, 'breed' => 42, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 4, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Bobtail (28KG - 42KG)'),
    array('type' => 1, 'breed' => 43, 'min_male' => 7, 5, 'min_female' => 7, 5, 'avg' => 7, 5, 'size' => 3, 'min_weight' => '6', 'max_weight' => '9', 'breed_name' => 'Bodeguero Andaluz (9KG - 13KG)'),
    array('type' => 1, 'breed' => 44, 'min_male' => 70, 'min_female' => 70, 'avg' => 70, 'size' => 5, 'min_weight' => '56', 'max_weight' => '84', 'breed_name' => 'Boerboel (56KG - 84KG)'),
    array('type' => 1, 'breed' => 45, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Border collie (12KG - 18KG)'),
    array('type' => 1, 'breed' => 46, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Border Terrier (5.1KG - 7.1KG)'),
    array('type' => 1, 'breed' => 47, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 6, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Borzoi (galgo ruso) (28KG - 42KG)'),
    array('type' => 1, 'breed' => 48, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Boston terrier (4.8KG - 10.2KG)'),
    array('type' => 1, 'breed' => 49, 'min_male' => 30, 'min_female' => 24, 'avg' => 27, 'size' => 4, 'min_weight' => '21,6', 'max_weight' => '32,4', 'breed_name' => 'Bóxer (21.6KG - 35.4KG)'),
    array('type' => 1, 'breed' => 50, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Boyero Australiano (16KG - 24KG)'),
    array('type' => 1, 'breed' => 51, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Boyero de Appenzell (22KG - 32KG)'),
    array('type' => 1, 'breed' => 52, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Boyero de Berna (36KG - 54KG)'),
    array('type' => 1, 'breed' => 53, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 3, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Boyero de Entlebuch (11.2KG - 16.8KG)'),
    array('type' => 1, 'breed' => 54, 'min_male' => 35, 'min_female' => 27, 'avg' => 31, 'size' => 4, 'min_weight' => '24,8', 'max_weight' => '37,2', 'breed_name' => 'Boyero de Flandes (24.8KG - 37.2KG)'),
    array('type' => 1, 'breed' => 55, 'min_male' => 28, 'min_female' => 22, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Boyero de las Ardenas (20KG - 30KG)'),
    array('type' => 1, 'breed' => 56, 'min_male' => 19, 'min_female' => 19, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Braco alemán de pelo corto (Kurzhaar) (22.2KG - 32.8KG)'),
    array('type' => 1, 'breed' => 57, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 4, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Braco alemán de pelo corto (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 58, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 4, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Braco Alemán de Pelo Duro (20KG - 32KG)'),
    array('type' => 1, 'breed' => 59, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Braco austriaco negro y fuego (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 60, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 4, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Braco de Ariège (20KG - 30KG)'),
    array('type' => 1, 'breed' => 61, 'min_male' => 22, 'min_female' => 22, 'avg' => 22, 'size' => 3, 'min_weight' => '17,6', 'max_weight' => '26,4', 'breed_name' => 'Braco de Auvernia (17.6KG - 26.4KG)'),
    array('type' => 1, 'breed' => 62, 'min_male' => 18, 'min_female' => 16, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Braco de Borbón (13.6KG - 22.4KG)'),
    array('type' => 1, 'breed' => 63, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 4, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'Braco de Weimar (25KG - 35KG)'),
    array('type' => 1, 'breed' => 66, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 4, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Braco eslovaco de pelo duro (20KG - 30KG)'),
    array('type' => 1, 'breed' => 67, 'min_male' => 17, 'min_female' => 17, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Braco francés (17.6KG - 25.4KG)'),
    array('type' => 1, 'breed' => 68, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 4, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Braco húngaro (Vizsla) (20KG - 30KG)'),
    array('type' => 1, 'breed' => 69, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 4, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Braco Italiano (25KG - 40KG)'),
    array('type' => 1, 'breed' => 70, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Braco Saint-Germain (16KG - 24KG)'),
    array('type' => 1, 'breed' => 71, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Briquet grifón vendeano (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 72, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Broholmer (36KG - 64KG)'),
    array('type' => 1, 'breed' => 73, 'min_male' => 14, 'min_female' => 12, 'avg' => 13, 'size' => 2, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Buhund noruego (10.4KG - 15.6KG)'),
    array('type' => 1, 'breed' => 74, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Bull Terrier (20KG - 30KG)'),
    array('type' => 1, 'breed' => 75, 'min_male' => 13, 'min_female' => 13, 'avg' => 13, 'size' => 2, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Bull Terrier miniatura (10.4KG - 15.6KG)'),
    array('type' => 1, 'breed' => 77, 'min_male' => 41, 'min_female' => 31, 'avg' => 36, 'size' => 4, 'min_weight' => '28,8', 'max_weight' => '43,2', 'breed_name' => 'Bulldog Americano (28.8KG - 53.2KG))'),
    array('type' => 1, 'breed' => 78, 'min_male' => 9, 'min_female' => 8, 'avg' => 8, 5, 'size' => 2, 'min_weight' => '6,8', 'max_weight' => '10,2', 'breed_name' => 'Bulldog francés (6.8KG - 10.2KG)'),
    array('type' => 1, 'breed' => 79, 'min_male' => 23, 'min_female' => 21, 'avg' => 22, 'size' => 3, 'min_weight' => '17,6', 'max_weight' => '26,4', 'breed_name' => 'Bulldog inglés (17.6KG - 26.4KG)'),
    array('type' => 1, 'breed' => 80, 'min_male' => 50, 'min_female' => 41, 'avg' => 45, 5, 'size' => 4, 'min_weight' => '36,4', 'max_weight' => '54,6', 'breed_name' => 'Bullmastiff (36.4KG - 54.6KG)'),
    array('type' => 1, 'breed' => 81, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Cairn Terrier (5KG - 7.5KG)),'),
    array('type' => 1, 'breed' => 82, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 4, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Calupoh (28KG - 42KG)'),
    array('type' => 1, 'breed' => 84, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Caniche Toy (Poodle) (2.5KG - 4.5KG)'),
    array('type' => 1, 'breed' => 85, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Carlino (Pug) (4.8KG - 7.2KG))'),
    array('type' => 1, 'breed' => 86, 'min_male' => 47, 'min_female' => 42, 'avg' => 44, 5, 'size' => 4, 'min_weight' => '35,6', 'max_weight' => '53,4', 'breed_name' => 'Carne Corso (35.6KG - 53.4KG)'),
    array('type' => 1, 'breed' => 87, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Cavalier King Charles Spaniel (5.9KG - 8.2KG)'),
    array('type' => 1, 'breed' => 88, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Cazador de alces noruego (16KG - 24KG)'),
    array('type' => 1, 'breed' => 89, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Chihuahua (1.6KG - 2.8KG)'),
    array('type' => 1, 'breed' => 90, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Chow Chow (16KG - 30KG)'),
    array('type' => 1, 'breed' => 91, 'min_male' => 40, 'min_female' => 40, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Cimarrón Utuguayo (32KG - 48KG)'),
    array('type' => 1, 'breed' => 92, 'min_male' => 10, 'min_female' => 8, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Cirneco del Etna (7.2KG - 12.8KG)'),
    array('type' => 1, 'breed' => 93, 'min_male' => 29, 'min_female' => 25, 'avg' => 27, 'size' => 3, 'min_weight' => '21,6', 'max_weight' => '32,4', 'breed_name' => 'Clumber Spaniel (24.6KG - 37.4KG)'),
    array('type' => 1, 'breed' => 94, 'min_male' => 27, 'min_female' => 25, 'avg' => 26, 'size' => 4, 'min_weight' => '20,8', 'max_weight' => '31,2', 'breed_name' => 'Cobrador de pelo liso (24.8KG - 35.2KG)'),
    array('type' => 1, 'breed' => 95, 'min_male' => 28, 'min_female' => 24, 'avg' => 26, 'size' => 4, 'min_weight' => '20,8', 'max_weight' => '31,2', 'breed_name' => 'Cobrador de pelo rizado (25.8KG - 36.2KG)'),
    array('type' => 1, 'breed' => 97, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 2, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Cocker Spaniel americano (8.6KG - 11.4KG)'),
    array('type' => 1, 'breed' => 98, 'min_male' => 13, 'min_female' => 13, 'avg' => 13, 'size' => 2, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Cocker Spaniel inglés (10.4KG - 15.6KG)'),
    array('type' => 1, 'breed' => 99, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Collie barbudo (16KG - 24KG)'),
    array('type' => 1, 'breed' => 100, 'min_male' => 20, 'min_female' => 18, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Collie de pelo corto (15.2KG - 25.8KG)'),
    array('type' => 1, 'breed' => 101, 'min_male' => 20, 'min_female' => 17, 'avg' => 18, 5, 'size' => 3, 'min_weight' => '14,8', 'max_weight' => '22,2', 'breed_name' => 'Collie de pelo largo (15.8KG - 28.2KG)'),
    array('type' => 1, 'breed' => 102, 'min_male' => 15, 'min_female' => 11, 'avg' => 13, 'size' => 3, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Corgi galés de Cardigan (10.4KG - 15.6KG)'),
    array('type' => 1, 'breed' => 103, 'min_male' => 10, 'min_female' => 9, 'avg' => 9, 5, 'size' => 3, 'min_weight' => '7,6', 'max_weight' => '11,4', 'breed_name' => 'Corgi galés de Pembroke (9KG - 13KG)'),
    array('type' => 1, 'breed' => 104, 'min_male' => 4, 'min_female' => 3, 'avg' => 3, 5, 'size' => 1, 'min_weight' => '2,8', 'max_weight' => '4,2', 'breed_name' => 'Cotón de Tulear (2.8KG - 5.2KG)'),
    array('type' => 1, 'breed' => 105, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 2, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Crestado chino (4KG - 9KG)'),
    array('type' => 1, 'breed' => 106, 'min_male' => 32, 'min_female' => 32, 'avg' => 32, 'size' => 4, 'min_weight' => '25,6', 'max_weight' => '38,4', 'breed_name' => 'Crestado rodesiano (25.6KG - 38.4KG)'),
    array('type' => 1, 'breed' => 108, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Cursinu (20KG - 30KG)'),
    array('type' => 1, 'breed' => 109, 'min_male' => 24, 'min_female' => 24, 'avg' => 24, 'size' => 3, 'min_weight' => '19,2', 'max_weight' => '28,8', 'breed_name' => 'Dálmata (19.2KG - 28.8KG)'),
    array('type' => 1, 'breed' => 110, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Dandie Dinmont Terrier (6.4KG - 9.6KG)'),
    array('type' => 1, 'breed' => 111, 'min_male' => 40, 'min_female' => 32, 'avg' => 36, 'size' => 4, 'min_weight' => '28,8', 'max_weight' => '43,2', 'breed_name' => 'Dóberman (28.8KG - 43.2KG)'),
    array('type' => 1, 'breed' => 112, 'min_male' => 40, 'min_female' => 40, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Dogo argentino (32KG - 48KG)'),
    array('type' => 1, 'breed' => 113, 'min_male' => 50, 'min_female' => 45, 'avg' => 47, 5, 'size' => 4, 'min_weight' => '38', 'max_weight' => '57', 'breed_name' => 'Dogo de Burdeos (48KG - 67KG)'),
    array('type' => 1, 'breed' => 114, 'min_male' => 55, 'min_female' => 55, 'avg' => 55, 'size' => 5, 'min_weight' => '44', 'max_weight' => '66', 'breed_name' => 'Dogo del Tíbet (44KG - 66KG)'),
    array('type' => 1, 'breed' => 115, 'min_male' => 35, 'min_female' => 30, 'avg' => 32, 5, 'size' => 4, 'min_weight' => '26', 'max_weight' => '39', 'breed_name' => 'Dogo mallorquín (26KG - 39KG)'),
    array('type' => 1, 'breed' => 116, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Drever (Perro tejonero sueco) (12KG - 18KG)'),
    array('type' => 1, 'breed' => 117, 'min_male' => 23, 'min_female' => 18, 'avg' => 20, 5, 'size' => 3, 'min_weight' => '16,4', 'max_weight' => '24,6', 'breed_name' => 'Eurasier (16.4KG - 30.6KG)'),
    array('type' => 1, 'breed' => 118, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Field Spaniel (18KG - 25KG)'),
    array('type' => 1, 'breed' => 119, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Fila Brasileiro (40KG - 74KG)'),
    array('type' => 1, 'breed' => 120, 'min_male' => 25, 'min_female' => 20, 'avg' => 22, 5, 'size' => 3, 'min_weight' => '18', 'max_weight' => '27', 'breed_name' => 'Fila de San Miguel (18KG - 35KG)'),
    array('type' => 1, 'breed' => 121, 'min_male' => 7, 'min_female' => 6, 'avg' => 6, 5, 'size' => 2, 'min_weight' => '5,2', 'max_weight' => '7,8', 'breed_name' => 'Fox Terrier pelo liso (5.2KG - 8.8KG)'),
    array('type' => 1, 'breed' => 122, 'min_male' => 2, 5, 'min_female' => 2, 5, 'avg' => 2, 5, 'size' => 1, 'min_weight' => '2', 'max_weight' => '3', 'breed_name' => 'Fox Terrier Toy (2KG - 3KG)'),
    array('type' => 1, 'breed' => 124, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Foxhound inglés (20KG - 30KG)'),
    array('type' => 1, 'breed' => 125, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 6, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Galgo afgano (26KG - 34KG)'),
    array('type' => 1, 'breed' => 126, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 6, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Galgo español (20KG - 30KG)'),
    array('type' => 1, 'breed' => 127, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 6, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Galgo inglés (25.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 128, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 6, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Galgo italiano (2.4KG - 7.6KG)'),
    array('type' => 1, 'breed' => 129, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 6, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Galgo polaco (28KG - 42KG)'),
    array('type' => 1, 'breed' => 130, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Gascon saintongeois (24KG - 36KG)'),
    array('type' => 1, 'breed' => 132, 'min_male' => 28, 'min_female' => 24, 'avg' => 26, 'size' => 3, 'min_weight' => '20,8', 'max_weight' => '31,2', 'breed_name' => 'Golden Retriever (20.8KG - 31.2KG)'),
    array('type' => 1, 'breed' => 133, 'min_male' => 29, 'min_female' => 25, 'avg' => 27, 'size' => 3, 'min_weight' => '21,6', 'max_weight' => '32,4', 'breed_name' => 'Gordon Setter (21.6KG - 32.4KG)'),
    array('type' => 1, 'breed' => 134, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Gran basset grifón vendeano (20KG - 30KG)'),
    array('type' => 1, 'breed' => 135, 'min_male' => 35, 'min_female' => 30, 'avg' => 32, 5, 'size' => 4, 'min_weight' => '26', 'max_weight' => '39', 'breed_name' => 'Gran boyero suizo (35KG - 60KG)'),
    array('type' => 1, 'breed' => 136, 'min_male' => 50, 'min_female' => 45, 'avg' => 47, 5, 'size' => 4, 'min_weight' => '38', 'max_weight' => '57', 'breed_name' => 'Gran danés (40KG - 90KG)'),
    array('type' => 1, 'breed' => 137, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Gran grifón vendeano (24KG - 36KG)'),
    array('type' => 1, 'breed' => 139, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Gran sabueso anglo-francés blanco y naranja (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 140, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Gran sabueso anglo-francés blanco y negro (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 141, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Gran sabueso anglo-francés tricolor (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 142, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Grifón de Bruselas (3.6KG - 5.4KG)'),
    array('type' => 1, 'breed' => 143, 'min_male' => 28, 'min_female' => 22, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Grifón de muestra Korthals o bohemio de pelo duro (20KG - 30KG)'),
    array('type' => 1, 'breed' => 145, 'min_male' => 27, 'min_female' => 27, 'avg' => 27, 'size' => 3, 'min_weight' => '21,6', 'max_weight' => '32,4', 'breed_name' => 'Grifon de muestra eslovaco (21.6KG - 32.4KG)'),
    array('type' => 1, 'breed' => 147, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Grifón leonado de Bretaña (14.4KG - 25.6KG)'),
    array('type' => 1, 'breed' => 148, 'min_male' => 23, 'min_female' => 23, 'avg' => 23, 'size' => 3, 'min_weight' => '18,4', 'max_weight' => '27,6', 'breed_name' => 'Grifón Nivernais (18.4KG - 27.6KG)'),
    array('type' => 1, 'breed' => 149, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Harrier (20KG - 30KG)'),
    array('type' => 1, 'breed' => 150, 'min_male' => 20, 'min_female' => 18, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Hokkaido (15.2KG - 22.8KG)'),
    array('type' => 1, 'breed' => 151, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Hovawart (25KG - 40KG)'),
    array('type' => 1, 'breed' => 152, 'min_male' => 20, 'min_female' => 15, 'avg' => 17, 5, 'size' => 3, 'min_weight' => '14', 'max_weight' => '21', 'breed_name' => 'Husky siberiano (14KG - 25KG)'),
    array('type' => 1, 'breed' => 154, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Jack Russell Terrier (5KG - 11KG)'),
    array('type' => 1, 'breed' => 155, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Jämthund (20KG - 30KG)'),
    array('type' => 1, 'breed' => 156, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Kai (12KG - 18KG)'),
    array('type' => 1, 'breed' => 157, 'min_male' => 50, 'min_female' => 50, 'avg' => 50, 'size' => 5, 'min_weight' => '40', 'max_weight' => '60', 'breed_name' => 'Kangal (40KG - 60KG)'),
    array('type' => 1, 'breed' => 158, 'min_male' => 25, 'min_female' => 17, 'avg' => 21, 'size' => 3, 'min_weight' => '16,8', 'max_weight' => '25,2', 'breed_name' => 'Karjalankarhukoira (Perro de osos de Carelia) (17.8KG - 25.2KG)),'),
    array('type' => 1, 'breed' => 159, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Keeshond (12KG - 18KG)'),
    array('type' => 1, 'breed' => 160, 'min_male' => 13, 'min_female' => 11, 'avg' => 12, 'size' => 2, 'min_weight' => '9,6', 'max_weight' => '14,4', 'breed_name' => 'Kelpie australiano (9.6KG - 24.4KG)'),
    array('type' => 1, 'breed' => 161, 'min_male' => 25, 'min_female' => 14, 'avg' => 19, 5, 'size' => 3, 'min_weight' => '15,6', 'max_weight' => '23,4', 'breed_name' => 'Kerry Blue Terrier (15KG - 20KG)'),
    array('type' => 1, 'breed' => 163, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Kishu (16KG - 24KG)'),
    array('type' => 1, 'breed' => 164, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Komondor (36KG - 60KG)'),
    array('type' => 1, 'breed' => 165, 'min_male' => 9, 'min_female' => 9, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Kromfohrländer (7.2KG - 10.8KG)'),
    array('type' => 1, 'breed' => 166, 'min_male' => 48, 'min_female' => 37, 'avg' => 42, 5, 'size' => 4, 'min_weight' => '34', 'max_weight' => '51', 'breed_name' => 'Kuvasz (34KG - 56KG)'),
    array('type' => 1, 'breed' => 167, 'min_male' => 35, 'min_female' => 30, 'avg' => 32, 5, 'size' => 4, 'min_weight' => '26', 'max_weight' => '39', 'breed_name' => 'Labrador Retriever (26KG - 39KG)'),
    array('type' => 1, 'breed' => 168, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Labsky (16KG - 24KG)'),
    array('type' => 1, 'breed' => 169, 'min_male' => 13, 'min_female' => 11, 'avg' => 12, 'size' => 3, 'min_weight' => '9,6', 'max_weight' => '14,4', 'breed_name' => 'Lagotto Romagnolo (10KG - 15KG)'),
    array('type' => 1, 'breed' => 171, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Laika de Siberia oriental (16KG - 24KG)'),
    array('type' => 1, 'breed' => 172, 'min_male' => 21, 'min_female' => 21, 'avg' => 21, 'size' => 3, 'min_weight' => '16,8', 'max_weight' => '25,2', 'breed_name' => 'Laika Ruso (16.8KG - 25.2KG)'),
    array('type' => 1, 'breed' => 173, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Laika ruso europeo (16KG - 24KG)'),
    array('type' => 1, 'breed' => 174, 'min_male' => 7, 'min_female' => 6, 'avg' => 6, 5, 'size' => 2, 'min_weight' => '5,2', 'max_weight' => '7,8', 'breed_name' => 'Lakeland Terrier (5.2KG - 7.8KG)'),
    array('type' => 1, 'breed' => 175, 'min_male' => 50, 'min_female' => 50, 'avg' => 50, 'size' => 5, 'min_weight' => '40', 'max_weight' => '60', 'breed_name' => 'Landseer (45KG - 70KG)'),
    array('type' => 1, 'breed' => 176, 'min_male' => 45, 'min_female' => 36, 'avg' => 40, 5, 'size' => 4, 'min_weight' => '32,4', 'max_weight' => '48,6', 'breed_name' => 'Lebrel escocés (32.4KG - 48.6KG)'),
    array('type' => 1, 'breed' => 177, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Lebrel húngaro (20KG - 30KG)'),
    array('type' => 1, 'breed' => 178, 'min_male' => 40, 'min_female' => 40, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Lebrel irlandés (38KG - 58KG)'),
    array('type' => 1, 'breed' => 179, 'min_male' => 55, 'min_female' => 45, 'avg' => 50, 'size' => 5, 'min_weight' => '40', 'max_weight' => '60', 'breed_name' => 'Leonberger (40KG - 65KG)'),
    array('type' => 1, 'breed' => 180, 'min_male' => 5, 'min_female' => 4, 'avg' => 4, 5, 'size' => 1, 'min_weight' => '3,6', 'max_weight' => '5,4', 'breed_name' => 'Lhasa Apso (4.6KG - 7.4KG)'),
    array('type' => 1, 'breed' => 181, 'min_male' => 6, 'min_female' => 5, 'avg' => 5, 5, 'size' => 2, 'min_weight' => '4,4', 'max_weight' => '6,6', 'breed_name' => 'Lundehund (4.4KG - 6.6KG)'),
    array('type' => 1, 'breed' => 183, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Maltipoo (3KG - 6KG)'),
    array('type' => 1, 'breed' => 184, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 2, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Manchester Terrier (5.6KG - 8.4KG)'),
    array('type' => 1, 'breed' => 185, 'min_male' => 55, 'min_female' => 55, 'avg' => 55, 'size' => 5, 'min_weight' => '44', 'max_weight' => '66', 'breed_name' => 'Mastín del Pirineo (44KG - 95KG)'),
    array('type' => 1, 'breed' => 186, 'min_male' => 60, 'min_female' => 60, 'avg' => 60, 'size' => 5, 'min_weight' => '48', 'max_weight' => '72', 'breed_name' => 'Mastín español (55KG - 100KG)'),
    array('type' => 1, 'breed' => 187, 'min_male' => 85, 'min_female' => 65, 'avg' => 75, 'size' => 5, 'min_weight' => '60', 'max_weight' => '90', 'breed_name' => 'Mastín inglés (60KG - 90KG)'),
    array('type' => 1, 'breed' => 188, 'min_male' => 60, 'min_female' => 50, 'avg' => 55, 'size' => 5, 'min_weight' => '44', 'max_weight' => '66', 'breed_name' => 'Mastín napolitano (44KG - 66KG)'),
    array('type' => 1, 'breed' => 189, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 4, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Mucuchíes (28KG - 42KG)'),
    array('type' => 1, 'breed' => 190, 'min_male' => 11, 'min_female' => 8, 'avg' => 9, 5, 'size' => 2, 'min_weight' => '7,6', 'max_weight' => '11,4', 'breed_name' => 'Mudi (7.6KG - 11.4KG)'),
    array('type' => 1, 'breed' => 191, 'min_male' => 24, 'min_female' => 24, 'avg' => 24, 'size' => 3, 'min_weight' => '19,2', 'max_weight' => '28,8', 'breed_name' => 'Münsterländer grande (19.2KG - 30.8KG)'),
    array('type' => 1, 'breed' => 192, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Münsterländer pequeño (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 193, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 3, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Otterhound (24KG - 36KG)'),
    array('type' => 1, 'breed' => 194, 'min_male' => 1, 'min_female' => 1, 'avg' => 1, 'size' => 1, 'min_weight' => '0,8', 'max_weight' => '1,2', 'breed_name' => 'Papillón (3.2KG - 4.5KG)'),
    array('type' => 1, 'breed' => 195, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Parson Russell Terrier (5KG - 8KG)'),
    array('type' => 1, 'breed' => 196, 'min_male' => 30, 'min_female' => 22, 'avg' => 26, 'size' => 3, 'min_weight' => '20,8', 'max_weight' => '31,2', 'breed_name' => 'Pastor alemán (20.8KG - 38.2KG)'),
    array('type' => 1, 'breed' => 197, 'min_male' => 25, 'min_female' => 20, 'avg' => 22, 5, 'size' => 3, 'min_weight' => '18', 'max_weight' => '27', 'breed_name' => 'Pastor belga (20KG - 30KG)'),
    array('type' => 1, 'breed' => 198, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 3, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'Pastor Blanco Suizo (22KG - 38KG)'),
    array('type' => 1, 'breed' => 199, 'min_male' => 18, 'min_female' => 16, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Pastor catalán (13.6KG - 20.4KG)'),
    array('type' => 1, 'breed' => 200, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Pastor croata (12KG - 18KG)'),
    array('type' => 1, 'breed' => 202, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Pastor de Asia central (39KG - 74KG)'),
    array('type' => 1, 'breed' => 203, 'min_male' => 40, 'min_female' => 40, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Pastor de Bosnia-Herzegovina y Croacia (32KG - 48KG)'),
    array('type' => 1, 'breed' => 204, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Pastor de Brie (24KG - 38KG)'),
    array('type' => 1, 'breed' => 205, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 3, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'Pastor de Karst (22KG - 33KG)'),
    array('type' => 1, 'breed' => 206, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 2, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Pastor de las islas Shetland (5.6KG - 8.4KG)'),
    array('type' => 1, 'breed' => 207, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Perro pastor de los Pirineos de pelo largo (6.4KG - 14.6KG)'),
    array('type' => 1, 'breed' => 208, 'min_male' => 35, 'min_female' => 30, 'avg' => 32, 5, 'size' => 4, 'min_weight' => '26', 'max_weight' => '39', 'breed_name' => 'Pastor de Maremma (26KG - 39KG)'),
    array('type' => 1, 'breed' => 211, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Pastor Polaco de Tatra (14KG - 26KG)'),
    array('type' => 1, 'breed' => 212, 'min_male' => 50, 'min_female' => 45, 'avg' => 47, 5, 'size' => 4, 'min_weight' => '38', 'max_weight' => '57', 'breed_name' => 'Pastor del Cáucaso (38KG - 57KG)'),
    array('type' => 1, 'breed' => 213, 'min_male' => 36, 'min_female' => 31, 'avg' => 33, 5, 'size' => 4, 'min_weight' => '26,8', 'max_weight' => '40,2', 'breed_name' => 'Pastor eslovaco (Cuvac Eslovaco) (26.8KG - 40.2KG)),'),
    array('type' => 1, 'breed' => 214, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Pastor finlandés de Laponia (LAPINPOROKOIRA) (15KG - 25KG)'),
    array('type' => 1, 'breed' => 216, 'min_male' => 25, 'min_female' => 20, 'avg' => 22, 5, 'size' => 3, 'min_weight' => '18', 'max_weight' => '27', 'breed_name' => 'Pastor holandés (21KG - 34KG)'),
    array('type' => 1, 'breed' => 217, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Pastor islandés (8KG - 12KG)'),
    array('type' => 1, 'breed' => 218, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Pastor lapón de Suecia (12KG - 18KG)'),
    array('type' => 1, 'breed' => 219, 'min_male' => 17, 'min_female' => 17, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Pastor Leonés (13.6KG - 25.4KG)'),
    array('type' => 1, 'breed' => 220, 'min_male' => 38, 'min_female' => 38, 'avg' => 38, 'size' => 4, 'min_weight' => '30,4', 'max_weight' => '45,6', 'breed_name' => 'Ca de bestiar - Pastor mallorquín (30.4KG - 45.6KG)'),
    array('type' => 1, 'breed' => 221, 'min_male' => 25, 'min_female' => 19, 'avg' => 22, 'size' => 3, 'min_weight' => '17,6', 'max_weight' => '26,4', 'breed_name' => 'Pastor ovejero australiano (16KG - 32KG)),'),
    array('type' => 1, 'breed' => 222, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Pastor polaco de las llanuras (12KG - 20KG)'),
    array('type' => 1, 'breed' => 223, 'min_male' => 45, 'min_female' => 45, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Pastor polaco de Podhale (36KG - 54KG)'),
    array('type' => 1, 'breed' => 225, 'min_male' => 45, 'min_female' => 35, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Pastor portugués (32KG - 48KG)'),
    array('type' => 1, 'breed' => 226, 'min_male' => 45, 'min_female' => 40, 'avg' => 42, 5, 'size' => 4, 'min_weight' => '34', 'max_weight' => '51', 'breed_name' => 'Pastor rumano de Mioritza (34KG - 51KG)'),
    array('type' => 1, 'breed' => 227, 'min_male' => 50, 'min_female' => 43, 'avg' => 46, 5, 'size' => 4, 'min_weight' => '37,2', 'max_weight' => '55,8', 'breed_name' => 'Pastor ucraniano (37.2KG - 55.8KG)'),
    array('type' => 1, 'breed' => 228, 'min_male' => 35, 'min_female' => 30, 'avg' => 32, 5, 'size' => 4, 'min_weight' => '26', 'max_weight' => '39', 'breed_name' => 'Perro de Pastor Yugoslavo (Sarplaninac) (26KG - 39KG)'),
    array('type' => 1, 'breed' => 229, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Pekinés (3KG - 6.6KG)),'),
    array('type' => 1, 'breed' => 230, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 2, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Pequeño Basset Grifón vendeano (11.2KG - 16.8KG)'),
    array('type' => 1, 'breed' => 231, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Pequeño Brabantino (2.4KG - 3.6KG)'),
    array('type' => 1, 'breed' => 232, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Pequeño Brabanzón (2.8KG - 3.8KG)'),
    array('type' => 1, 'breed' => 233, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Pequeño perro león (4KG - 6KG)'),
    array('type' => 1, 'breed' => 234, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Pequeño perro ruso (1.6KG - 2.4KG)'),
    array('type' => 1, 'breed' => 235, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Pequeño sabueso de Suiza (8KG - 12KG)'),
    array('type' => 1, 'breed' => 236, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Perdiguero alemán (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 237, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Perdiguero de Burgos (20KG - 30KG)'),
    array('type' => 1, 'breed' => 238, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 3, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'Perdiguero de Drente (22KG - 33KG)'),
    array('type' => 1, 'breed' => 239, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Perdiguero frisón (19.4KG - 26.6KG)'),
    array('type' => 1, 'breed' => 240, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Perdiguero navarro (20KG - 30KG)'),
    array('type' => 1, 'breed' => 241, 'min_male' => 20, 'min_female' => 16, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Perdiguero portugués (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 242, 'min_male' => 13, 'min_female' => 11, 'avg' => 12, 'size' => 2, 'min_weight' => '9,6', 'max_weight' => '14,4', 'breed_name' => 'Perro de agua americano (9.6KG - 17.4KG)'),
    array('type' => 1, 'breed' => 243, 'min_male' => 28, 'min_female' => 14, 'avg' => 21, 'size' => 3, 'min_weight' => '16,8', 'max_weight' => '25,2', 'breed_name' => 'Perro de agua español (16.8KG - 25.2KG)'),
    array('type' => 1, 'breed' => 245, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Perro de agua frisón (16KG - 24KG)'),
    array('type' => 1, 'breed' => 246, 'min_male' => 22, 'min_female' => 21, 'avg' => 21, 5, 'size' => 3, 'min_weight' => '17,2', 'max_weight' => '25,8', 'breed_name' => 'Perro de agua irlandés (19.2KG - 28.8KG)),'),
    array('type' => 1, 'breed' => 247, 'min_male' => 19, 'min_female' => 16, 'avg' => 17, 5, 'size' => 3, 'min_weight' => '14', 'max_weight' => '21', 'breed_name' => 'Perro de agua portugués (16KG - 25KG)'),
    array('type' => 1, 'breed' => 248, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Perro de Canaán (18KG - 25KG)),'),
    array('type' => 1, 'breed' => 249, 'min_male' => 30, 'min_female' => 25, 'avg' => 27, 5, 'size' => 3, 'min_weight' => '22', 'max_weight' => '33', 'breed_name' => 'Perro de Castro Laboreiro (24KG - 40KG)'),
    array('type' => 1, 'breed' => 251, 'min_male' => 18, 'min_female' => 15, 'avg' => 16, 5, 'size' => 3, 'min_weight' => '13,2', 'max_weight' => '19,8', 'breed_name' => 'Perro de Jindo (13.2KG - 12.8KG)'),
    array('type' => 1, 'breed' => 252, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Perro de Groenlandia (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 253, 'min_male' => 45, 'min_female' => 35, 'avg' => 40, 'size' => 4, 'min_weight' => '32', 'max_weight' => '48', 'breed_name' => 'Perro de la Sierra de la Estrela (32KG - 48KG)'),
    array('type' => 1, 'breed' => 254, 'min_male' => 14, 'min_female' => 12, 'avg' => 13, 'size' => 2, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Perro de montaña de Formosa (10.4KG - 15.6KG)'),
    array('type' => 1, 'breed' => 255, 'min_male' => 56, 'min_female' => 50, 'avg' => 53, 'size' => 5, 'min_weight' => '42,4', 'max_weight' => '63,6', 'breed_name' => 'Perro de montaña de los Pirineos (42.4KG - 63.6KG)'),
    array('type' => 1, 'breed' => 256, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Perro de Montaña del Atlas (20KG - 30KG)'),
    array('type' => 1, 'breed' => 257, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Perro de muestra alemán de pelo cerdoso (20KG - 30KG)'),
    array('type' => 1, 'breed' => 261, 'min_male' => 11, 'min_female' => 11, 'avg' => 11, 'size' => 2, 'min_weight' => '8,8', 'max_weight' => '13,2', 'breed_name' => 'Perro esquimal Americano (8.8KG - 13.2KG)'),
    array('type' => 1, 'breed' => 262, 'min_male' => 30, 'min_female' => 18, 'avg' => 24, 'size' => 3, 'min_weight' => '19,2', 'max_weight' => '28,8', 'breed_name' => 'Perro esquimal canadiense (19.2KG - 28.8KG)'),
    array('type' => 1, 'breed' => 264, 'min_male' => 26, 'min_female' => 20, 'avg' => 23, 'size' => 4, 'min_weight' => '18,4', 'max_weight' => '27,6', 'breed_name' => 'Perro lobo checoslovaco (20KG - 35KG)'),
    array('type' => 1, 'breed' => 265, 'min_male' => 38, 'min_female' => 34, 'avg' => 36, 'size' => 4, 'min_weight' => '28,8', 'max_weight' => '43,2', 'breed_name' => 'Perro lobo de Saarloos (28.8KG - 43.2KG)'),
    array('type' => 1, 'breed' => 266, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Perro sin pelo del Perú (3.2KG - 25KG)'),
    array('type' => 1, 'breed' => 267, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Perro smous holandes (7KG - 12KG)'),
    array('type' => 1, 'breed' => 268, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 2, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Perro tejonero de Westfalia (13.2KG - 19.8KG)'),
    array('type' => 1, 'breed' => 269, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Pharaoh Hound (16KG - 26KG)'),
    array('type' => 1, 'breed' => 270, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 2, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Pinscher (13.2KG - 19.8KG)'),
    array('type' => 1, 'breed' => 271, 'min_male' => 12, 'min_female' => 12, 'avg' => 12, 'size' => 2, 'min_weight' => '9,6', 'max_weight' => '14,4', 'breed_name' => 'Pinscher austríaco (9.6KG - 14.4KG)'),
    array('type' => 1, 'breed' => 272, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Pinscher miniatura (3.2KG - 5.8KG)'),
    array('type' => 1, 'breed' => 273, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Plott hound (16KG - 27KG)'),
    array('type' => 1, 'breed' => 274, 'min_male' => 23, 'min_female' => 23, 'avg' => 23, 'size' => 6, 'min_weight' => '18,4', 'max_weight' => '27,6', 'breed_name' => 'Podenco canario (18.4KG - 27.6KG)'),
    array('type' => 1, 'breed' => 275, 'min_male' => 19, 'min_female' => 19, 'avg' => 19, 'size' => 6, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Podenco ibicenco (15.2KG - 22.8KG)'),
    array('type' => 1, 'breed' => 276, 'min_male' => 16, 'min_female' => 16, 'avg' => 16, 'size' => 6, 'min_weight' => '12,8', 'max_weight' => '19,2', 'breed_name' => 'Podenco portugués (4 KG - 30KG)'),
    array('type' => 1, 'breed' => 277, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Pointer inglés (16KG - 28KG)'),
    array('type' => 1, 'breed' => 278, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Poitevino (24KG - 36KG)'),
    array('type' => 1, 'breed' => 279, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Pomerania (2.4KG - 3.6KG)'),
    array('type' => 1, 'breed' => 280, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Poochon (3.2KG - 4.8KG)'),
    array('type' => 1, 'breed' => 281, 'min_male' => 30, 'min_female' => 20, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Porcelana (20KG - 30KG)'),
    array('type' => 1, 'breed' => 282, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Presa Canario (36KG - 57KG)'),
    array('type' => 1, 'breed' => 283, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Pudelpointer (20KG - 30KG)'),
    array('type' => 1, 'breed' => 284, 'min_male' => 13, 'min_female' => 10, 'avg' => 11, 5, 'size' => 2, 'min_weight' => '9,2', 'max_weight' => '13,8', 'breed_name' => 'Puli (9.2KG - 15)'),
    array('type' => 1, 'breed' => 285, 'min_male' => 10, 'min_female' => 8, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Pumi (7.2KG - 10.8KG)'),
    array('type' => 1, 'breed' => 286, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 4, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Rafeiro do Alentejo (35KG - 60KG)'),
    array('type' => 1, 'breed' => 287, 'min_male' => 38, 'min_female' => 38, 'avg' => 38, 'size' => 4, 'min_weight' => '30,4', 'max_weight' => '45,6', 'breed_name' => 'Rastreador de Hannover (25.4KG - 45.6KG)'),
    array('type' => 1, 'breed' => 288, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Rastreador montañés de Baviera (16KG - 30KG)'),
    array('type' => 1, 'breed' => 290, 'min_male' => 29, 'min_female' => 25, 'avg' => 27, 'size' => 3, 'min_weight' => '21,6', 'max_weight' => '32,4', 'breed_name' => 'Retriever de Chesapeake (21.6KG - 35.4KG)'),
    array('type' => 1, 'breed' => 292, 'min_male' => 20, 'min_female' => 17, 'avg' => 18, 5, 'size' => 3, 'min_weight' => '14,8', 'max_weight' => '22,2', 'breed_name' => 'Retriever de Nueva Escocia (16.8KG - 23KG)'),
    array('type' => 1, 'breed' => 295, 'min_male' => 25, 'min_female' => 20, 'avg' => 22, 5, 'size' => 3, 'min_weight' => '18', 'max_weight' => '27', 'breed_name' => 'Ridgeback tailandés (18KG - 27KG)'),
    array('type' => 1, 'breed' => 296, 'min_male' => 45, 'min_female' => 42, 'avg' => 43, 5, 'size' => 4, 'min_weight' => '34,8', 'max_weight' => '52,2', 'breed_name' => 'Rottweiler (36.8KG - 52.2KG)'),
    array('type' => 1, 'breed' => 297, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso alemán (16KG - 24KG)'),
    array('type' => 1, 'breed' => 298, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Sabueso anglo-francés de tamaño mediano (20KG - 30KG)'),
    array('type' => 1, 'breed' => 299, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Sabueso artesiano (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 300, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso austríaco negro y fuego (14.4KG - 26.6KG)'),
    array('type' => 1, 'breed' => 302, 'min_male' => 16, 'min_female' => 16, 'avg' => 16, 'size' => 3, 'min_weight' => '12,8', 'max_weight' => '19,2', 'breed_name' => 'Sabueso de Bosnia de pelo cerdoso (14.8KG - 24.2KG)'),
    array('type' => 1, 'breed' => 303, 'min_male' => 23, 'min_female' => 23, 'avg' => 23, 'size' => 3, 'min_weight' => '18,4', 'max_weight' => '27,6', 'breed_name' => 'Sabueso de Hamilton (18.4KG - 27.6KG)'),
    array('type' => 1, 'breed' => 305, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso de Hygen (16KG - 24KG)'),
    array('type' => 1, 'breed' => 306, 'min_male' => 46, 'min_female' => 46, 'avg' => 46, 'size' => 4, 'min_weight' => '36,8', 'max_weight' => '55,2', 'breed_name' => 'Sabueso de Istria de pelo corto (14.8KG - 21.2KG)'),
    array('type' => 1, 'breed' => 307, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso de Istria de pelo duro (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 308, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso de montaña de Montenegro (16KG - 24KG)'),
    array('type' => 1, 'breed' => 310, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Sabueso de Småland (12KG - 18KG)'),
    array('type' => 1, 'breed' => 311, 'min_male' => 30, 'min_female' => 30, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Sabueso de Transilvania (25KG - 36KG)'),
    array('type' => 1, 'breed' => 312, 'min_male' => 28, 'min_female' => 28, 'avg' => 28, 'size' => 3, 'min_weight' => '22,4', 'max_weight' => '33,6', 'breed_name' => 'Sabueso del Ariège (22.4KG - 33.6KG)'),
    array('type' => 1, 'breed' => 313, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso del Tirol (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 314, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso del Valle de Save (16KG - 24KG)'),
    array('type' => 1, 'breed' => 315, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Sabueso eslovaco (12KG - 18KG)'),
    array('type' => 1, 'breed' => 316, 'min_male' => 24, 'min_female' => 24, 'avg' => 24, 'size' => 3, 'min_weight' => '19,2', 'max_weight' => '28,8', 'breed_name' => 'Sabueso español (19.2KG - 28.8KG)'),
    array('type' => 1, 'breed' => 317, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso estirio de pelo áspero (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 318, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Sabueso finlandés (20KG - 30KG)'),
    array('type' => 1, 'breed' => 319, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Sabueso francés blanco y naranja (20KG - 30KG)'),
    array('type' => 1, 'breed' => 320, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Sabueso francés blanco y negro (22KG - 32KG)'),
    array('type' => 1, 'breed' => 321, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Sabueso francés tricolor (25KG - 36KG)'),
    array('type' => 1, 'breed' => 322, 'min_male' => 23, 'min_female' => 20, 'avg' => 21, 5, 'size' => 3, 'min_weight' => '17,2', 'max_weight' => '25,8', 'breed_name' => 'Sabueso Halden (17.2KG - 25.8KG)'),
    array('type' => 1, 'breed' => 323, 'min_male' => 17, 'min_female' => 17, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Sabueso helénico (13.6KG - 20.4KG)'),
    array('type' => 1, 'breed' => 325, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso italiano de pelo raso (16KG - 28KG)'),
    array('type' => 1, 'breed' => 326, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso italiano de pelo duro (16.4KG - 27.6KG)'),
    array('type' => 1, 'breed' => 327, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso noruego (16KG - 24KG)'),
    array('type' => 1, 'breed' => 328, 'min_male' => 25, 'min_female' => 20, 'avg' => 22, 5, 'size' => 3, 'min_weight' => '18', 'max_weight' => '27', 'breed_name' => 'Sabueso polaco (18KG - 27KG)'),
    array('type' => 1, 'breed' => 329, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Sabueso Schiller (14.4KG - 23.6KG)'),
    array('type' => 1, 'breed' => 330, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso serbio (16KG - 24KG)'),
    array('type' => 1, 'breed' => 331, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Sabueso suizo (Schweizer Laufhund) (12KG - 18KG)'),
    array('type' => 1, 'breed' => 332, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sabueso tricolor serbio (16KG - 24KG)'),
    array('type' => 1, 'breed' => 333, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 6, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Saluki (galgo persa) (12KG - 23KG)'),
    array('type' => 1, 'breed' => 334, 'min_male' => 20, 'min_female' => 15, 'avg' => 17, 5, 'size' => 3, 'min_weight' => '14', 'max_weight' => '21', 'breed_name' => 'Samoyedo (16KG - 31KG)'),
    array('type' => 1, 'breed' => 335, 'min_male' => 55, 'min_female' => 50, 'avg' => 52, 5, 'size' => 5, 'min_weight' => '42', 'max_weight' => '63', 'breed_name' => 'San Bernardo (52KG - 82KG)'),
    array('type' => 1, 'breed' => 337, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Schapendoes neerlandés (8KG - 12KG)'),
    array('type' => 1, 'breed' => 338, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Schipperke (2.4KG - 9KG)'),
    array('type' => 1, 'breed' => 339, 'min_male' => 14, 'min_female' => 14, 'avg' => 14, 'size' => 2, 'min_weight' => '11,2', 'max_weight' => '16,8', 'breed_name' => 'Schnauzer (14.2KG - 18.8KG)'),
    array('type' => 1, 'breed' => 340, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Schnauzer gigante (20KG - 47KG)'),
    array('type' => 1, 'breed' => 341, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Schnauzer miniatura (4KG - 8KG)'),
    array('type' => 1, 'breed' => 342, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Sealyham terrier (6.4KG - 9.6KG)'),
    array('type' => 1, 'breed' => 343, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Setter inglés (18KG - 34KG)'),
    array('type' => 1, 'breed' => 344, 'min_male' => 20, 'min_female' => 18, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Setter irlandés (23.2KG - 32.8KG)'),
    array('type' => 1, 'breed' => 345, 'min_male' => 20, 'min_female' => 18, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Setter irlandés rojo y blanco (25.2KG - 32.8KG)'),
    array('type' => 1, 'breed' => 346, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Shar Pei (17.4KG - 25.6KG)'),
    array('type' => 1, 'breed' => 347, 'min_male' => 25, 'min_female' => 25, 'avg' => 25, 'size' => 3, 'min_weight' => '20', 'max_weight' => '30', 'breed_name' => 'Shepsky (20KG - 30KG)'),
    array('type' => 1, 'breed' => 348, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 3, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Shiba Inu (6.5KG - 12KG)'),
    array('type' => 1, 'breed' => 349, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Shih Tzu (4.5KG - 7.5KG)'),
    array('type' => 1, 'breed' => 350, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Shikoku Inu (13KG - 22KG)'),
    array('type' => 1, 'breed' => 352, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Skye Terrier (8KG - 12KG)'),
    array('type' => 1, 'breed' => 353, 'min_male' => 20, 'min_female' => 19, 'avg' => 19, 5, 'size' => 6, 'min_weight' => '15,6', 'max_weight' => '23,4', 'breed_name' => 'Sloughi (galgo árabe) (15.6KG - 23.4KG)'),
    array('type' => 1, 'breed' => 354, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Spaniel azul de Picardía (12KG - 18KG)'),
    array('type' => 1, 'breed' => 355, 'min_male' => 13, 'min_female' => 13, 'avg' => 13, 'size' => 2, 'min_weight' => '10,4', 'max_weight' => '15,6', 'breed_name' => 'Spaniel bretón (10.4KG - 19.6KG)'),
    array('type' => 1, 'breed' => 356, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Spaniel enano continental (Phalene) (2.6KG - 5.4KG)'),
    array('type' => 1, 'breed' => 357, 'min_male' => 17, 'min_female' => 17, 'avg' => 17, 'size' => 3, 'min_weight' => '13,6', 'max_weight' => '20,4', 'breed_name' => 'Spaniel de Pont-Audemer (13.6KG - 24.4KG)),'),
    array('type' => 1, 'breed' => 359, 'min_male' => 24, 'min_female' => 24, 'avg' => 24, 'size' => 3, 'min_weight' => '19,2', 'max_weight' => '28,8', 'breed_name' => 'Spaniel francés (19.2KG - 28.8KG)'),
    array('type' => 1, 'breed' => 360, 'min_male' => 10, 'min_female' => 10, 'avg' => 10, 'size' => 2, 'min_weight' => '8', 'max_weight' => '12', 'breed_name' => 'Spaniel holandés (8KG - 12KG)'),
    array('type' => 1, 'breed' => 361, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Spaniel japonés (2.4KG - 3.6KG)'),
    array('type' => 1, 'breed' => 362, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Spaniel picardo (18.4KG - 24.6KG)'),
    array('type' => 1, 'breed' => 363, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Spaniel tibetano (3.2KG - 6.8KG)'),
    array('type' => 1, 'breed' => 364, 'min_male' => 32, 'min_female' => 28, 'avg' => 30, 'size' => 4, 'min_weight' => '24', 'max_weight' => '36', 'breed_name' => 'Spinone italiano (24KG - 37KG)'),
    array('type' => 1, 'breed' => 365, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 2, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Spitz alemán (2.6KG - 28KG)'),
    array('type' => 1, 'breed' => 366, 'min_male' => 9, 'min_female' => 9, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Spitz de Norrbotten (7.2KG - 10.8KG)'),
    array('type' => 1, 'breed' => 367, 'min_male' => 12, 'min_female' => 7, 'avg' => 9, 5, 'size' => 2, 'min_weight' => '7,6', 'max_weight' => '11,4', 'breed_name' => 'Spitz finlandés (7.6KG - 15.4KG)),'),
    array('type' => 1, 'breed' => 368, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Spitz japonés (4.8KG - 9.2KG)'),
    array('type' => 1, 'breed' => 369, 'min_male' => 18, 'min_female' => 15, 'avg' => 16, 5, 'size' => 3, 'min_weight' => '13,2', 'max_weight' => '19,8', 'breed_name' => 'Springer spaniel galés (13.2KG - 19.8KG)'),
    array('type' => 1, 'breed' => 370, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Springer Spaniel inglés (14.4KG - 24.6KG)'),
    array('type' => 1, 'breed' => 371, 'min_male' => 12, 'min_female' => 11, 'avg' => 11, 5, 'size' => 2, 'min_weight' => '9,2', 'max_weight' => '13,8', 'breed_name' => 'Staffordshire bull terrier (9.2KG - 15.8KG)'),
    array('type' => 1, 'breed' => 372, 'min_male' => 20, 'min_female' => 20, 'avg' => 20, 'size' => 3, 'min_weight' => '16', 'max_weight' => '24', 'breed_name' => 'Sussex Spaniel (16KG - 24KG)'),
    array('type' => 1, 'breed' => 374, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Teckel (9KG - 15KG)'),
    array('type' => 1, 'breed' => 377, 'min_male' => 60, 'min_female' => 50, 'avg' => 55, 'size' => 5, 'min_weight' => '44', 'max_weight' => '66', 'breed_name' => 'Terranova (50KG - 70KG)'),
    array('type' => 1, 'breed' => 379, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Terrier australiano (2.4KG - 7KG)'),
    array('type' => 1, 'breed' => 380, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Terrier brasileño (6.4KG - 9.6KG)'),
    array('type' => 1, 'breed' => 381, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 2, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Terrier cazador alemán (5.6KG - 9.4KG)'),
    array('type' => 1, 'breed' => 382, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Terrier checo (4.8KG - 7.2KG)'),
    array('type' => 1, 'breed' => 384, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Terrier de Norfolk (4KG - 5.5KG)'),
    array('type' => 1, 'breed' => 385, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Terrier de Norwich (4KG - 6KG)'),
    array('type' => 1, 'breed' => 386, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Terrier escocés (8.5KG - 10.5KG)),'),
    array('type' => 1, 'breed' => 387, 'min_male' => 9, 'min_female' => 9, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Terrier galés (7.2KG - 10.8KG)'),
    array('type' => 1, 'breed' => 388, 'min_male' => 15, 'min_female' => 15, 'avg' => 15, 'size' => 3, 'min_weight' => '12', 'max_weight' => '18', 'breed_name' => 'Terrier Glen de Imaal irlandés (12KG - 18KG)'),
    array('type' => 1, 'breed' => 389, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Terrier inglés miniatura negro y fuego (1.6KG - 3.6KG)'),
    array('type' => 1, 'breed' => 390, 'min_male' => 11, 'min_female' => 11, 'avg' => 11, 'size' => 2, 'min_weight' => '8,8', 'max_weight' => '13,2', 'breed_name' => 'Terrier irlandés (8.8KG - 13.2KG)'),
    array('type' => 1, 'breed' => 391, 'min_male' => 18, 'min_female' => 18, 'avg' => 18, 'size' => 3, 'min_weight' => '14,4', 'max_weight' => '21,6', 'breed_name' => 'Terrier irlandés de pelo suave (14.4KG - 21.6KG)'),
    array('type' => 1, 'breed' => 392, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Terrier japonés (3.2KG - 4.8KG)'),
    array('type' => 1, 'breed' => 393, 'min_male' => 35, 'min_female' => 35, 'avg' => 35, 'size' => 4, 'min_weight' => '28', 'max_weight' => '42', 'breed_name' => 'Terrier ruso negro (45KG - 60KG)'),
    array('type' => 1, 'breed' => 394, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 2, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Terrier tibetano (6.4KG - 10.6KG)'),
    array('type' => 1, 'breed' => 395, 'min_male' => 50, 'min_female' => 40, 'avg' => 45, 'size' => 4, 'min_weight' => '36', 'max_weight' => '54', 'breed_name' => 'Tosa Inu (36KG - 54KG)'),
    array('type' => 1, 'breed' => 396, 'min_male' => 9, 'min_female' => 9, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Vallhund sueco (7.2KG - 14.8KG)'),
    array('type' => 1, 'breed' => 397, 'min_male' => 20, 'min_female' => 18, 'avg' => 19, 'size' => 3, 'min_weight' => '15,2', 'max_weight' => '22,8', 'breed_name' => 'Vizsla (15.2KG - 22.8KG)'),
    array('type' => 1, 'breed' => 398, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Volpino italiano (3.2KG - 5.6KG)'),
    array('type' => 1, 'breed' => 399, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 2, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'West Highland White Terrier (5.8KG - 9.2KG)'),
    array('type' => 1, 'breed' => 401, 'min_male' => 9, 'min_female' => 9, 'avg' => 9, 'size' => 6, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Whippet (7.2KG - 12.8KG)'),
    array('type' => 1, 'breed' => 403, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Xoloitzcuintle toy (2.4KG - 8.6KG)'),
    array('type' => 1, 'breed' => 404, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Yorkshire Terrier (1.6KG - 4.8KG)'),
    array('type' => 1, 'breed' => 406, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 3, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Pastor belga (20KG - 30KG)'),
    array('type' => 1, 'breed' => 407, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 2, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Teckel miniatura (5KG - 9KG)'),
    array('type' => 1, 'breed' => 408, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Teckel Kaninchen (3KG - 5KG)'),
    array('type' => 1, 'breed' => 409, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 2, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Fox Terrier pelo alambre (6KG - 9 KG)'),
    array('type' => 1, 'breed' => 410, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Caniche Enano (Poodle) (4.2KG - 7.2KG)'),
    array('type' => 1, 'breed' => 411, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 2, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Caniche Mediano (Poodle) (7KG - 15KG)'),
    array('type' => 1, 'breed' => 412, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 3, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Caniche Grande (Poodle) (15KG - 25KG)'),
    array('type' => 1, 'breed' => 413, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 2, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Xoloitzcuintle mediano (9KG - 17KG)'),
    array('type' => 1, 'breed' => 414, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 3, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Xoloitzcuintle estandar (18KG - 25KG)'),  
    array('type' => 2, 'breed' => 1, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Mezcla (4KG - 6KG)'),
    array('type' => 2, 'breed' => 2, 'min_male' => 7, 'min_female' => 7, 'avg' => 7, 'size' => 1, 'min_weight' => '5,6', 'max_weight' => '8,4', 'breed_name' => 'Abisinio (5.6KG - 8.4KG)'),
    array('type' => 2, 'breed' => 3, 'min_male' => 2, 'min_female' => 2, 'avg' => 2, 'size' => 1, 'min_weight' => '1,6', 'max_weight' => '2,4', 'breed_name' => 'Africano doméstico (1.6KG - 2.4KG)'),
    array('type' => 2, 'breed' => 4, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'American Curl (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 5, 'min_male' => 6, 'min_female' => 4, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'American shorthair (4KG - 6KG)'),
    array('type' => 2, 'breed' => 6, 'min_male' => 7, 'min_female' => 5, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'American wirehair (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 7, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Angora turco (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 8, 'min_male' => 5, 'min_female' => 3, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Azul ruso (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 9, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 2, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Bengala (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 10, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Bobtail japonés (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 11, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Bombay (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 12, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Bosque de Noruega (4KG - 6KG)'),
    array('type' => 2, 'breed' => 13, 'min_male' => 7, 'min_female' => 3, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Brazilian Shorthair (4KG - 6KG)'),
    array('type' => 2, 'breed' => 14, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'British Longhair (4KG - 6KG)'),
    array('type' => 2, 'breed' => 15, 'min_male' => 7, 'min_female' => 5, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'British Shorthair (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 16, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Burmés (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 17, 'min_male' => 7, 'min_female' => 5, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Burmilla (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 18, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'California Spangled (4KG - 6KG)'),
    array('type' => 2, 'breed' => 19, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Carey (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 20, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Chartreux (4KG - 6KG)'),
    array('type' => 2, 'breed' => 21, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Cornish rex (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 22, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Cymric (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 23, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Deutsch Langhaar (4KG - 6KG)'),
    array('type' => 2, 'breed' => 24, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Devon rex (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 25, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Don Sphynx (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 26, 'min_male' => 13, 'min_female' => 5, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Dorado africano (7.2KG - 10.8KG)'),
    array('type' => 2, 'breed' => 27, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Dragon Li (4KG - 6KG)'),
    array('type' => 2, 'breed' => 28, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Europeo bicolor (4KG - 6KG)'),
    array('type' => 2, 'breed' => 29, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Europeo Común (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 30, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Exótico de Pelo Corto (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 31, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'FoldEx (4KG - 6KG)'),
    array('type' => 2, 'breed' => 32, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'German Rex (4KG - 6KG)'),
    array('type' => 2, 'breed' => 33, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Habana brown (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 34, 'min_male' => 10, 'min_female' => 8, 'avg' => 9, 'size' => 2, 'min_weight' => '7,2', 'max_weight' => '10,8', 'breed_name' => 'Himalayo (7.2KG - 10.8KG)'),
    array('type' => 2, 'breed' => 35, 'min_male' => 5, 'min_female' => 3, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Khao Manee (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 36, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Korat (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 37, 'min_male' => 6, 'min_female' => 4, 'avg' => 5, 'size' => 2, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Maine Coon (4KG - 6KG)'),
    array('type' => 2, 'breed' => 38, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Manx (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 39, 'min_male' => 6, 'min_female' => 4, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Mau egipcio (4KG - 6KG)'),
    array('type' => 2, 'breed' => 40, 'min_male' => 5, 'min_female' => 3, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Munchkin (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 41, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Ocicat (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 42, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Oriental (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 43, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Oriental de pelo largo (4KG - 6KG)'),
    array('type' => 2, 'breed' => 44, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Persa Americano o Moderno (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 45, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Peterbald (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 46, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Pixie Bob (4KG - 6KG)'),
    array('type' => 2, 'breed' => 47, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Ragdoll (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 48, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Rojo (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 49, 'min_male' => 4, 'min_female' => 5, 'avg' => 4, 5, 'size' => 1, 'min_weight' => '3,6', 'max_weight' => '5,4', 'breed_name' => 'Sagrado de Birmania (3.6KG - 5.4KG)'),
    array('type' => 2, 'breed' => 50, 'min_male' => 8, 'min_female' => 8, 'avg' => 8, 'size' => 1, 'min_weight' => '6,4', 'max_weight' => '9,6', 'breed_name' => 'Savannah (6.4KG - 9.6KG)'),
    array('type' => 2, 'breed' => 51, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Scottish Fold (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 52, 'min_male' => 5, 'min_female' => 5, 'avg' => 5, 'size' => 1, 'min_weight' => '4', 'max_weight' => '6', 'breed_name' => 'Selkirk rex (4KG - 6KG)'),
    array('type' => 2, 'breed' => 53, 'min_male' => 7, 'min_female' => 5, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Serengeti (4.8KG - 7.2KG)'),
    array('type' => 2, 'breed' => 54, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Seychellois (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 55, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Siamés (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 56, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Siamés Moderno (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 57, 'min_male' => 4, 'min_female' => 4, 'avg' => 4, 'size' => 1, 'min_weight' => '3,2', 'max_weight' => '4,8', 'breed_name' => 'Siamés Tradicional (3.2KG - 4.8KG)'),
    array('type' => 2, 'breed' => 58, 'min_male' => 7, 'min_female' => 6, 'avg' => 6, 5, 'size' => 1, 'min_weight' => '5,2', 'max_weight' => '7,8', 'breed_name' => 'Siberiano (5.2KG - 7.8KG)'),
    array('type' => 2, 'breed' => 59, 'min_male' => 4, 'min_female' => 3, 'avg' => 3, 5, 'size' => 1, 'min_weight' => '2,8', 'max_weight' => '4,2', 'breed_name' => 'Snowshoe (2.8KG - 4.2KG)'),
    array('type' => 2, 'breed' => 60, 'min_male' => 4, 'min_female' => 5, 'avg' => 4, 5, 'size' => 1, 'min_weight' => '3,6', 'max_weight' => '5,4', 'breed_name' => 'Sphynx (3.6KG - 5.4KG)'),
    array('type' => 2, 'breed' => 61, 'min_male' => 3, 'min_female' => 3, 'avg' => 3, 'size' => 1, 'min_weight' => '2,4', 'max_weight' => '3,6', 'breed_name' => 'Tonkinés (2.4KG - 3.6KG)'),
    array('type' => 2, 'breed' => 62, 'min_male' => 6, 'min_female' => 6, 'avg' => 6, 'size' => 1, 'min_weight' => '4,8', 'max_weight' => '7,2', 'breed_name' => 'Van Turco (4.8KG - 7.2KG)')
);