<?php


$_html = '';

$_html .= '<div class="panel">

				<div class="panel-heading"><i class="fa fa-question-circle fa-lg"></i>&nbsp;'.$this->_data_translate_custom['_help_documentation_help_doc'].'</div>';

$_html .= '<b style="text-transform:uppercase">'.$this->_data_translate_custom['_help_documentation_mod_doc'].':</b>&nbsp;<a target="_blank" href="../modules/'.$this->name.'/Installation_Guid.pdf" style="text-decoration:underline;font-weight:bold">Installation_Guid.pdf</a>
    			';
$_html .= '</div>';


echo $_html;

?>