<?php


$res = '';
$product_count = $count;
$res .= '<div class="b-pager">';
$res .= '<dl>';
$res .= '<dt>'.$this->l('Page').':</dt>';

$start1 = $start;
for ($start1 = ($start - $step*4 >= 0 ? $start - $step*4 : 0); $start1 < ($start + $step*5 < $product_count ? $start + $step*5 : $product_count); $start1 += $step)
{
    $par = (int)($start1 / $step) + 1;
    if ($start1 == $start)
    {

        $res .= '<dd class="current"><a href="#">'. $par .'</a></dd>';
    }
    else
    {
        $res .= '<dd>
										<a href="javascript:void(0)"
										   onclick="go_page_shoppers( '.($start1 ? $start1 : 0).' , '.$search.', \''.$query.'\' )"
										>'.$par.'</a>
									 </dd>';
    }
}

$res .= '</dl>';
$res .= '</div>';

echo $res;

?>